name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle
      - uses: android-actions/setup-android@v3
      - run: chmod +x ./gradlew
      - run: ./gradlew assembleDebug --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: KaloriTounsiPlus-debug-apk
          path: app/build/outputs/apk/debug/*.apk
